"""
Tool definitions for the SL Voice Agent.
"""
import io
import asyncio
import logging
from datetime import datetime

logger = logging.getLogger(__name__)


def web_search(query: str) -> str:
    """Search the web for up-to-date information.

    Use this tool whenever the user asks about current prices, events, availability,
    weather, exchange rates, or anything else that may have changed recently.
    Always append 'Sri Lanka' to the query if it is location-specific.

    Args:
        query: The search query string.

    Returns:
        A concise summary of the top search results.
    """
    try:
        from duckduckgo_search import DDGS

        results = DDGS().text(query, max_results=5)

        if not results:
            return "No results found for that query."

        lines = []
        for r in results:
            title = r.get("title", "").strip()
            body = r.get("body", "").strip()
            href = r.get("href", "").strip()
            if title or body:
                lines.append(f"- {title}: {body} ({href})")

        return "\n".join(lines) if lines else "No useful results found."

    except Exception as e:
        logger.error(f"web_search tool error: {e}")
        return f"Search failed: {e}"


def _build_itinerary_pdf(itinerary_text: str) -> bytes:
    """Renders the itinerary markdown-like text into a styled PDF and returns raw bytes."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
    from reportlab.lib.enums import TA_CENTER, TA_LEFT

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=2.5 * cm,
        bottomMargin=2.5 * cm,
    )

    styles = getSampleStyleSheet()
    gold = colors.HexColor("#C9A84C")
    dark = colors.HexColor("#1A1A2E")

    title_style = ParagraphStyle(
        "ItineraryTitle",
        parent=styles["Title"],
        fontSize=24,
        textColor=dark,
        spaceAfter=6,
        alignment=TA_CENTER,
    )
    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.HexColor("#666666"),
        spaceAfter=18,
        alignment=TA_CENTER,
    )
    heading_style = ParagraphStyle(
        "DayHeading",
        parent=styles["Heading2"],
        fontSize=14,
        textColor=gold,
        spaceBefore=14,
        spaceAfter=4,
        borderPad=4,
    )
    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=10,
        textColor=dark,
        leading=15,
        spaceAfter=4,
        alignment=TA_LEFT,
    )

    story = []
    story.append(Paragraph("🌴 Sri Lanka Travel Itinerary", title_style))
    story.append(Paragraph(f"Prepared by SL Bot · {datetime.now().strftime('%B %d, %Y')}", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=gold, spaceAfter=16))

    for line in itinerary_text.splitlines():
        stripped = line.strip()
        if not stripped:
            story.append(Spacer(1, 6))
        elif stripped.startswith("##"):
            story.append(Paragraph(stripped.lstrip("#").strip(), heading_style))
        elif stripped.startswith("#"):
            story.append(Paragraph(stripped.lstrip("#").strip(), heading_style))
        elif stripped.startswith("-") or stripped.startswith("•"):
            story.append(Paragraph(f"&nbsp;&nbsp;&nbsp;{stripped}", body_style))
        else:
            story.append(Paragraph(stripped, body_style))

    story.append(Spacer(1, 24))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#CCCCCC")))
    story.append(Paragraph("Generated by SL Bot Voice Assistant", subtitle_style))

    doc.build(story)
    return buf.getvalue()


def build_itinerary_tool(caller_phone: str):
    """
    Factory that returns a @function_tool closed over the caller's WhatsApp phone number.
    Call this once per voice session to create a session-specific tool instance.
    """

    async def send_itinerary_pdf(itinerary: str) -> str:
        """Prepare a Sri Lanka travel itinerary PDF and send it to the user's WhatsApp chat.

        Call this tool when the user asks you to share, send, or prepare their itinerary,
        or at the end of a planning conversation once you have assembled a full plan.

        Format the itinerary clearly using:
        - Lines starting with # or ## for day/section headings (e.g. "## Day 1 – Colombo")
        - Lines starting with - for bullet points (e.g. "- Visit the Galle Face Green")
        - Plain text lines for descriptions and notes
        - Include estimated costs in LKR where known

        Args:
            itinerary: The full itinerary text, using the formatting guidelines above.

        Returns:
            A confirmation message to relay to the user.
        """
        from app.services.whatsapp_api import whatsapp_api

        try:
            logger.info(f"Generating itinerary PDF for {caller_phone}")
            pdf_bytes = await asyncio.get_event_loop().run_in_executor(
                None, _build_itinerary_pdf, itinerary
            )

            filename = f"SL_Itinerary_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"

            media_id = await whatsapp_api.upload_media(pdf_bytes, "application/pdf", filename)
            if not media_id:
                return "I tried to send your itinerary but the upload failed. Please try again."

            success = await whatsapp_api.send_document(
                to=caller_phone,
                media_id=media_id,
                filename=filename,
                caption="Here's your Sri Lanka travel itinerary from SL Bot. Not that I enjoyed making it for you.",
            )

            if success:
                logger.info(f"Itinerary PDF sent to {caller_phone}")
                return "Your itinerary PDF has been sent to your WhatsApp chat."
            else:
                return "The PDF was prepared but I couldn't send it. Check your WhatsApp."

        except Exception as e:
            logger.error(f"send_itinerary_pdf error: {e}", exc_info=True)
            return f"Failed to generate the itinerary: {e}"

    return send_itinerary_pdf

